# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Nicob\Documents\maya\2020\scripts\rigBot\gui\applyMocap.ui',
# licensing of 'C:\Users\Nicob\Documents\maya\2020\scripts\rigBot\gui\applyMocap.ui' applies.
#
# Created: Thu Feb 25 09:17:17 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_applyMocap(object):
    def setupUi(self, applyMocap):
        applyMocap.setObjectName("applyMocap")
        applyMocap.resize(500, 573)
        applyMocap.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox_5 = QtWidgets.QGroupBox(applyMocap)
        self.groupBox_5.setGeometry(QtCore.QRect(17, 66, 460, 148))
        self.groupBox_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox_5.setObjectName("groupBox_5")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_5)
        self.splitter_2.setGeometry(QtCore.QRect(4, 17, 452, 124))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.path_line = QtWidgets.QLineEdit(self.layoutWidget1)
        self.path_line.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.path_line.setText("")
        self.path_line.setObjectName("path_line")
        self.verticalLayout_2.addWidget(self.path_line)
        self.rig_ns_line = QtWidgets.QLineEdit(self.layoutWidget1)
        self.rig_ns_line.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.rig_ns_line.setText("")
        self.rig_ns_line.setObjectName("rig_ns_line")
        self.verticalLayout_2.addWidget(self.rig_ns_line)
        self.mocap_ns_line = QtWidgets.QLineEdit(self.layoutWidget1)
        self.mocap_ns_line.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.mocap_ns_line.setText("")
        self.mocap_ns_line.setObjectName("mocap_ns_line")
        self.verticalLayout_2.addWidget(self.mocap_ns_line)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.import_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.import_btn.setObjectName("import_btn")
        self.verticalLayout_3.addWidget(self.import_btn)
        self.rig_ns_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.rig_ns_btn.setObjectName("rig_ns_btn")
        self.verticalLayout_3.addWidget(self.rig_ns_btn)
        self.mocap_ns_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.mocap_ns_btn.setObjectName("mocap_ns_btn")
        self.verticalLayout_3.addWidget(self.mocap_ns_btn)
        self.mocap_ns_btn_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.mocap_ns_btn_2.setEnabled(False)
        self.mocap_ns_btn_2.setText("")
        self.mocap_ns_btn_2.setObjectName("mocap_ns_btn_2")
        self.verticalLayout_3.addWidget(self.mocap_ns_btn_2)
        self.groupBox_4 = QtWidgets.QGroupBox(applyMocap)
        self.groupBox_4.setGeometry(QtCore.QRect(17, 7, 460, 54))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(49, 4, 410, 42))
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(57, 57, 57);\n"
"color: rgb(230, 230, 230);")
        self.label.setIndent(9)
        self.label.setObjectName("label")
        self.icon_label = QtWidgets.QLabel(self.groupBox_4)
        self.icon_label.setGeometry(QtCore.QRect(-5, 4, 54, 42))
        self.icon_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.icon_label.setFont(font)
        self.icon_label.setStyleSheet("background-color: rgb(57, 57, 57);\n"
"color: rgb(230, 230, 230);")
        self.icon_label.setText("")
        self.icon_label.setIndent(9)
        self.icon_label.setObjectName("icon_label")
        self.groupBox = QtWidgets.QGroupBox(applyMocap)
        self.groupBox.setGeometry(QtCore.QRect(16, 309, 469, 235))
        self.groupBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.l_leg_slider = QtWidgets.QSlider(self.groupBox)
        self.l_leg_slider.setMaximum(10)
        self.l_leg_slider.setPageStep(1)
        self.l_leg_slider.setOrientation(QtCore.Qt.Horizontal)
        self.l_leg_slider.setObjectName("l_leg_slider")
        self.horizontalLayout_4.addWidget(self.l_leg_slider)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.spine_slider = QtWidgets.QSlider(self.groupBox)
        self.spine_slider.setMaximum(10)
        self.spine_slider.setPageStep(1)
        self.spine_slider.setOrientation(QtCore.Qt.Horizontal)
        self.spine_slider.setObjectName("spine_slider")
        self.horizontalLayout_2.addWidget(self.spine_slider)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.neck_slider = QtWidgets.QSlider(self.groupBox)
        self.neck_slider.setMaximum(10)
        self.neck_slider.setPageStep(1)
        self.neck_slider.setOrientation(QtCore.Qt.Horizontal)
        self.neck_slider.setObjectName("neck_slider")
        self.horizontalLayout_3.addWidget(self.neck_slider)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_5.addWidget(self.label_18)
        self.l_arm_slider = QtWidgets.QSlider(self.groupBox)
        self.l_arm_slider.setMaximum(10)
        self.l_arm_slider.setPageStep(1)
        self.l_arm_slider.setOrientation(QtCore.Qt.Horizontal)
        self.l_arm_slider.setObjectName("l_arm_slider")
        self.horizontalLayout_5.addWidget(self.l_arm_slider)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.r_leg_slider = QtWidgets.QSlider(self.groupBox)
        self.r_leg_slider.setMaximum(10)
        self.r_leg_slider.setPageStep(1)
        self.r_leg_slider.setOrientation(QtCore.Qt.Horizontal)
        self.r_leg_slider.setObjectName("r_leg_slider")
        self.horizontalLayout_6.addWidget(self.r_leg_slider)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 1, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.r_arm_slider = QtWidgets.QSlider(self.groupBox)
        self.r_arm_slider.setMaximum(10)
        self.r_arm_slider.setPageStep(1)
        self.r_arm_slider.setOrientation(QtCore.Qt.Horizontal)
        self.r_arm_slider.setTickInterval(0)
        self.r_arm_slider.setObjectName("r_arm_slider")
        self.horizontalLayout_7.addWidget(self.r_arm_slider)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(applyMocap)
        self.groupBox_3.setGeometry(QtCore.QRect(16, 232, 464, 60))
        self.groupBox_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.all_connect_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.all_connect_btn.setObjectName("all_connect_btn")
        self.horizontalLayout.addWidget(self.all_connect_btn)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout.addWidget(self.label_22)
        self.all_slider = QtWidgets.QSlider(self.groupBox_3)
        self.all_slider.setMaximum(10)
        self.all_slider.setPageStep(1)
        self.all_slider.setOrientation(QtCore.Qt.Horizontal)
        self.all_slider.setObjectName("all_slider")
        self.horizontalLayout.addWidget(self.all_slider)

        self.retranslateUi(applyMocap)
        QtCore.QMetaObject.connectSlotsByName(applyMocap)

    def retranslateUi(self, applyMocap):
        applyMocap.setWindowTitle(QtCompat.translate("applyMocap", "Mocap Utils", None, -1))
        self.groupBox_5.setTitle(QtCompat.translate("applyMocap", "Mocap FBX", None, -1))
        self.label_14.setText(QtCompat.translate("applyMocap", "Import Mocap", None, -1))
        self.label_8.setText(QtCompat.translate("applyMocap", "Rig Namespace", None, -1))
        self.label_9.setText(QtCompat.translate("applyMocap", "Mocap NS", None, -1))
        self.label_21.setText(QtCompat.translate("applyMocap", "Start Frame", None, -1))
        self.import_btn.setText(QtCompat.translate("applyMocap", "...", None, -1))
        self.rig_ns_btn.setText(QtCompat.translate("applyMocap", "<<get", None, -1))
        self.mocap_ns_btn.setText(QtCompat.translate("applyMocap", "<< get", None, -1))
        self.label.setText(QtCompat.translate("applyMocap", "ApplyOptiTrack Mocap To Body Rig", None, -1))
        self.groupBox.setTitle(QtCompat.translate("applyMocap", "Blend", None, -1))
        self.label_6.setText(QtCompat.translate("applyMocap", "Neck/Head", None, -1))
        self.label_10.setText(QtCompat.translate("applyMocap", "Left  Leg", None, -1))
        self.label_12.setText(QtCompat.translate("applyMocap", "Left Arm", None, -1))
        self.label_17.setText(QtCompat.translate("applyMocap", "Blend", None, -1))
        self.label_3.setText(QtCompat.translate("applyMocap", "Spine/Chest", None, -1))
        self.label_15.setText(QtCompat.translate("applyMocap", "Blend", None, -1))
        self.label_16.setText(QtCompat.translate("applyMocap", "Blend", None, -1))
        self.label_13.setText(QtCompat.translate("applyMocap", "Right Arm", None, -1))
        self.label_18.setText(QtCompat.translate("applyMocap", "Blend", None, -1))
        self.label_19.setText(QtCompat.translate("applyMocap", "Blend", None, -1))
        self.label_20.setText(QtCompat.translate("applyMocap", "Blend", None, -1))
        self.label_11.setText(QtCompat.translate("applyMocap", "Right Leg", None, -1))
        self.groupBox_3.setTitle(QtCompat.translate("applyMocap", "Connect", None, -1))
        self.all_connect_btn.setText(QtCompat.translate("applyMocap", "Connect To Rig", None, -1))
        self.label_22.setText(QtCompat.translate("applyMocap", "global Blend", None, -1))

