# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/net/homes/bhamilton/maya/scripts/rigBot/gui/bakeVelocity.ui'
#
# Created: Wed May 30 16:26:01 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(279, 343)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(57, 57, 57);\n"
"color: rgb(230, 230, 230);")
        self.label.setIndent(9)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.gravityLine = QtWidgets.QLineEdit(self.groupBox)
        self.gravityLine.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.gravityLine.setObjectName("gravityLine")
        self.gridLayout.addWidget(self.gravityLine, 0, 1, 1, 1)
        self.massLine = QtWidgets.QLineEdit(self.groupBox)
        self.massLine.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.massLine.setObjectName("massLine")
        self.gridLayout.addWidget(self.massLine, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.rotLine = QtWidgets.QLineEdit(self.groupBox)
        self.rotLine.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.rotLine.setObjectName("rotLine")
        self.gridLayout.addWidget(self.rotLine, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.startLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.startLine.setObjectName("startLine")
        self.gridLayout_2.addWidget(self.startLine, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.endLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.endLine.setObjectName("endLine")
        self.gridLayout_2.addWidget(self.endLine, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.runupLine = QtWidgets.QLineEdit(self.groupBox_2)
        self.runupLine.setObjectName("runupLine")
        self.gridLayout_2.addWidget(self.runupLine, 2, 1, 1, 1)
        self.startBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.startBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.startBtn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_2.addWidget(self.startBtn, 0, 2, 1, 1)
        self.endBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.endBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.endBtn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.endBtn.setObjectName("endBtn")
        self.gridLayout_2.addWidget(self.endBtn, 1, 2, 1, 1)
        self.runupBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.runupBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.runupBtn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.runupBtn.setObjectName("runupBtn")
        self.gridLayout_2.addWidget(self.runupBtn, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.createBtn = QtWidgets.QPushButton(Form)
        self.createBtn.setObjectName("createBtn")
        self.verticalLayout.addWidget(self.createBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCompat.translate("Form", "Bake Velocity Utility", None, -1))
        self.label.setText(QtCompat.translate("Form", "Bake Velocity", None, -1))
        self.groupBox.setTitle(QtCompat.translate("Form", "Physical Properties", None, -1))
        self.label_2.setText(QtCompat.translate("Form", "Gravity", None, -1))
        self.gravityLine.setText(QtCompat.translate("Form", "9.8", None, -1))
        self.massLine.setText(QtCompat.translate("Form", "10.0", None, -1))
        self.label_7.setText(QtCompat.translate("Form", "Rotational Inertia", None, -1))
        self.label_3.setText(QtCompat.translate("Form", "Object Mass", None, -1))
        self.rotLine.setText(QtCompat.translate("Form", "0.5", None, -1))
        self.groupBox_2.setTitle(QtCompat.translate("Form", "Frame Range", None, -1))
        self.label_4.setText(QtCompat.translate("Form", "Start Frame", None, -1))
        self.label_5.setText(QtCompat.translate("Form", "End Frame", None, -1))
        self.label_6.setText(QtCompat.translate("Form", "Runup Start Frame ", None, -1))
        self.startBtn.setText(QtCompat.translate("Form", "<<", None, -1))
        self.endBtn.setText(QtCompat.translate("Form", "<<", None, -1))
        self.runupBtn.setText(QtCompat.translate("Form", "<<", None, -1))
        self.createBtn.setText(QtCompat.translate("Form", "Create", None, -1))

