# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/job/comms/pipeline/dev/bhamilton/git/ rigBot/rigBot/gui/cluster.ui'
#
# Created: Mon Aug 12 12:26:32 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_ClusterUI(object):
    def setupUi(self, ClusterUI):
        ClusterUI.setObjectName("ClusterUI")
        ClusterUI.resize(344, 562)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ClusterUI)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.assetLabel_2 = QtWidgets.QLabel(ClusterUI)
        self.assetLabel_2.setMinimumSize(QtCore.QSize(40, 30))
        self.assetLabel_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.assetLabel_2.setFont(font)
        self.assetLabel_2.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: rgb(40, 40,40);")
        self.assetLabel_2.setIndent(10)
        self.assetLabel_2.setObjectName("assetLabel_2")
        self.verticalLayout_4.addWidget(self.assetLabel_2)
        self.groupBox = QtWidgets.QGroupBox(ClusterUI)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.prebind_node_line = QtWidgets.QLineEdit(self.groupBox)
        self.prebind_node_line.setObjectName("prebind_node_line")
        self.gridLayout.addWidget(self.prebind_node_line, 2, 1, 1, 1)
        self.weighted_node_line = QtWidgets.QLineEdit(self.groupBox)
        self.weighted_node_line.setObjectName("weighted_node_line")
        self.gridLayout.addWidget(self.weighted_node_line, 1, 1, 1, 1)
        self.prebind_node_btn = QtWidgets.QPushButton(self.groupBox)
        self.prebind_node_btn.setObjectName("prebind_node_btn")
        self.gridLayout.addWidget(self.prebind_node_btn, 2, 2, 1, 1)
        self.weighted_node_btn = QtWidgets.QPushButton(self.groupBox)
        self.weighted_node_btn.setObjectName("weighted_node_btn")
        self.gridLayout.addWidget(self.weighted_node_btn, 1, 2, 1, 1)
        self.name_line = QtWidgets.QLineEdit(self.groupBox)
        self.name_line.setObjectName("name_line")
        self.gridLayout.addWidget(self.name_line, 0, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.create_btn = QtWidgets.QPushButton(self.groupBox)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout.addWidget(self.create_btn)
        self.create_soft_btn = QtWidgets.QPushButton(self.groupBox)
        self.create_soft_btn.setObjectName("create_soft_btn")
        self.verticalLayout.addWidget(self.create_soft_btn)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ClusterUI)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mirror_prebind_node_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_prebind_node_btn.setObjectName("mirror_prebind_node_btn")
        self.gridLayout_2.addWidget(self.mirror_prebind_node_btn, 2, 2, 1, 1)
        self.mirror_weighted_node_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_weighted_node_btn.setObjectName("mirror_weighted_node_btn")
        self.gridLayout_2.addWidget(self.mirror_weighted_node_btn, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.mirror_weighted_node_line = QtWidgets.QLineEdit(self.groupBox_2)
        self.mirror_weighted_node_line.setObjectName("mirror_weighted_node_line")
        self.gridLayout_2.addWidget(self.mirror_weighted_node_line, 1, 1, 1, 1)
        self.mirror_prebind_node_line = QtWidgets.QLineEdit(self.groupBox_2)
        self.mirror_prebind_node_line.setObjectName("mirror_prebind_node_line")
        self.gridLayout_2.addWidget(self.mirror_prebind_node_line, 2, 1, 1, 1)
        self.mirror_cluster_line = QtWidgets.QLineEdit(self.groupBox_2)
        self.mirror_cluster_line.setReadOnly(True)
        self.mirror_cluster_line.setObjectName("mirror_cluster_line")
        self.gridLayout_2.addWidget(self.mirror_cluster_line, 0, 1, 1, 1)
        self.mirror_weighted_node_btn_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_weighted_node_btn_2.setObjectName("mirror_weighted_node_btn_2")
        self.gridLayout_2.addWidget(self.mirror_weighted_node_btn_2, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.mirror_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_btn.setObjectName("mirror_btn")
        self.verticalLayout_2.addWidget(self.mirror_btn)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(ClusterUI)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.mod_cluster_line = QtWidgets.QLineEdit(self.groupBox_3)
        self.mod_cluster_line.setReadOnly(True)
        self.mod_cluster_line.setObjectName("mod_cluster_line")
        self.gridLayout_3.addWidget(self.mod_cluster_line, 0, 1, 1, 1)
        self.mirror_weighted_node_btn_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.mirror_weighted_node_btn_3.setObjectName("mirror_weighted_node_btn_3")
        self.gridLayout_3.addWidget(self.mirror_weighted_node_btn_3, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.add_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout_3.addWidget(self.add_btn)
        self.set_soft_weights_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.set_soft_weights_btn.setObjectName("set_soft_weights_btn")
        self.verticalLayout_3.addWidget(self.set_soft_weights_btn)
        self.connect_prebind_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.connect_prebind_btn.setObjectName("connect_prebind_btn")
        self.verticalLayout_3.addWidget(self.connect_prebind_btn)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 154, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)

        self.retranslateUi(ClusterUI)
        QtCore.QMetaObject.connectSlotsByName(ClusterUI)
        ClusterUI.setTabOrder(self.name_line, self.weighted_node_line)
        ClusterUI.setTabOrder(self.weighted_node_line, self.weighted_node_btn)
        ClusterUI.setTabOrder(self.weighted_node_btn, self.prebind_node_line)
        ClusterUI.setTabOrder(self.prebind_node_line, self.prebind_node_btn)
        ClusterUI.setTabOrder(self.prebind_node_btn, self.create_btn)
        ClusterUI.setTabOrder(self.create_btn, self.mirror_cluster_line)
        ClusterUI.setTabOrder(self.mirror_cluster_line, self.mirror_weighted_node_btn_2)
        ClusterUI.setTabOrder(self.mirror_weighted_node_btn_2, self.mirror_weighted_node_line)
        ClusterUI.setTabOrder(self.mirror_weighted_node_line, self.mirror_weighted_node_btn)
        ClusterUI.setTabOrder(self.mirror_weighted_node_btn, self.mirror_prebind_node_line)
        ClusterUI.setTabOrder(self.mirror_prebind_node_line, self.mirror_prebind_node_btn)
        ClusterUI.setTabOrder(self.mirror_prebind_node_btn, self.mirror_btn)
        ClusterUI.setTabOrder(self.mirror_btn, self.mod_cluster_line)
        ClusterUI.setTabOrder(self.mod_cluster_line, self.mirror_weighted_node_btn_3)
        ClusterUI.setTabOrder(self.mirror_weighted_node_btn_3, self.add_btn)
        ClusterUI.setTabOrder(self.add_btn, self.set_soft_weights_btn)
        ClusterUI.setTabOrder(self.set_soft_weights_btn, self.connect_prebind_btn)

    def retranslateUi(self, ClusterUI):
        ClusterUI.setWindowTitle(QtCompat.translate("ClusterUI", "Cluster UI", None, -1))
        self.assetLabel_2.setText(QtCompat.translate("ClusterUI", "Cluster UI", None, -1))
        self.groupBox.setTitle(QtCompat.translate("ClusterUI", "Create ", None, -1))
        self.label.setText(QtCompat.translate("ClusterUI", "Name", None, -1))
        self.label_2.setText(QtCompat.translate("ClusterUI", "Weighted Node", None, -1))
        self.label_3.setText(QtCompat.translate("ClusterUI", "Prebind Node", None, -1))
        self.prebind_node_btn.setText(QtCompat.translate("ClusterUI", "Get Selected", None, -1))
        self.weighted_node_btn.setText(QtCompat.translate("ClusterUI", "Get Selected", None, -1))
        self.create_btn.setText(QtCompat.translate("ClusterUI", "Create Cluster", None, -1))
        self.create_soft_btn.setText(QtCompat.translate("ClusterUI", "Cluster With Soft Selection Weights", None, -1))
        self.groupBox_2.setTitle(QtCompat.translate("ClusterUI", "Mirror", None, -1))
        self.mirror_prebind_node_btn.setText(QtCompat.translate("ClusterUI", "Get Selected", None, -1))
        self.mirror_weighted_node_btn.setText(QtCompat.translate("ClusterUI", "Get Selected", None, -1))
        self.label_4.setText(QtCompat.translate("ClusterUI", "Source Cluster", None, -1))
        self.label_5.setText(QtCompat.translate("ClusterUI", "New Weighted Node", None, -1))
        self.label_6.setText(QtCompat.translate("ClusterUI", "New Prebind Node", None, -1))
        self.mirror_weighted_node_btn_2.setText(QtCompat.translate("ClusterUI", "Get Selected", None, -1))
        self.mirror_btn.setText(QtCompat.translate("ClusterUI", "Mirror Cluster && Weights", None, -1))
        self.groupBox_3.setTitle(QtCompat.translate("ClusterUI", "Modify", None, -1))
        self.label_7.setText(QtCompat.translate("ClusterUI", "Source Cluster", None, -1))
        self.mirror_weighted_node_btn_3.setText(QtCompat.translate("ClusterUI", "Get Selected", None, -1))
        self.add_btn.setText(QtCompat.translate("ClusterUI", "Add Selection To Cluster", None, -1))
        self.set_soft_weights_btn.setText(QtCompat.translate("ClusterUI", "Set Weights From Soft Selection", None, -1))
        self.connect_prebind_btn.setText(QtCompat.translate("ClusterUI", "Connect Selected To Cluster Prebind", None, -1))

