# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bhamilton/Documents/maya/scripts\rigBot\gui\control.ui'
#
# Created: Sun Sep 16 21:58:55 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_ClusterUI(object):
    def setupUi(self, ClusterUI):
        ClusterUI.setObjectName("ClusterUI")
        ClusterUI.resize(314, 735)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ClusterUI)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.assetLabel_2 = QtWidgets.QLabel(ClusterUI)
        self.assetLabel_2.setMinimumSize(QtCore.QSize(40, 30))
        self.assetLabel_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.assetLabel_2.setFont(font)
        self.assetLabel_2.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: rgb(40, 40,40);")
        self.assetLabel_2.setIndent(10)
        self.assetLabel_2.setObjectName("assetLabel_2")
        self.verticalLayout_4.addWidget(self.assetLabel_2)
        self.groupBox = QtWidgets.QGroupBox(ClusterUI)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.pivot_chx = QtWidgets.QCheckBox(self.groupBox)
        self.pivot_chx.setObjectName("pivot_chx")
        self.gridLayout.addWidget(self.pivot_chx, 6, 1, 1, 3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.X_rdo = QtWidgets.QRadioButton(self.groupBox_5)
        self.X_rdo.setChecked(True)
        self.X_rdo.setObjectName("X_rdo")
        self.horizontalLayout_3.addWidget(self.X_rdo)
        self.Y_rdo = QtWidgets.QRadioButton(self.groupBox_5)
        self.Y_rdo.setChecked(False)
        self.Y_rdo.setObjectName("Y_rdo")
        self.horizontalLayout_3.addWidget(self.Y_rdo)
        self.Z_rdo = QtWidgets.QRadioButton(self.groupBox_5)
        self.Z_rdo.setObjectName("Z_rdo")
        self.horizontalLayout_3.addWidget(self.Z_rdo)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.groupBox_5, 5, 1, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.L_rdo = QtWidgets.QRadioButton(self.groupBox_6)
        self.L_rdo.setChecked(True)
        self.L_rdo.setObjectName("L_rdo")
        self.horizontalLayout_7.addWidget(self.L_rdo)
        self.R_rdo = QtWidgets.QRadioButton(self.groupBox_6)
        self.R_rdo.setChecked(False)
        self.R_rdo.setObjectName("R_rdo")
        self.horizontalLayout_7.addWidget(self.R_rdo)
        self.C_rdo = QtWidgets.QRadioButton(self.groupBox_6)
        self.C_rdo.setObjectName("C_rdo")
        self.horizontalLayout_7.addWidget(self.C_rdo)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout.addWidget(self.groupBox_6, 0, 1, 1, 2)
        self.name_line = QtWidgets.QLineEdit(self.groupBox)
        self.name_line.setObjectName("name_line")
        self.gridLayout.addWidget(self.name_line, 1, 1, 1, 3)
        self.shape_cmb = QtWidgets.QComboBox(self.groupBox)
        self.shape_cmb.setStyleSheet("QComboBox{background-color:rgb(45,45,45);}")
        self.shape_cmb.setObjectName("shape_cmb")
        self.gridLayout.addWidget(self.shape_cmb, 2, 1, 1, 3)
        self.color_cmb = QtWidgets.QComboBox(self.groupBox)
        self.color_cmb.setStyleSheet("QComboBox{background-color:rgb(45,45,45);}")
        self.color_cmb.setObjectName("color_cmb")
        self.gridLayout.addWidget(self.color_cmb, 3, 1, 1, 3)
        self.snap_chx = QtWidgets.QCheckBox(self.groupBox)
        self.snap_chx.setChecked(True)
        self.snap_chx.setObjectName("snap_chx")
        self.gridLayout.addWidget(self.snap_chx, 7, 1, 1, 3)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.transform_rdo = QtWidgets.QRadioButton(self.groupBox_7)
        self.transform_rdo.setChecked(True)
        self.transform_rdo.setObjectName("transform_rdo")
        self.horizontalLayout_9.addWidget(self.transform_rdo)
        self.joint_rdo = QtWidgets.QRadioButton(self.groupBox_7)
        self.joint_rdo.setChecked(False)
        self.joint_rdo.setObjectName("joint_rdo")
        self.horizontalLayout_9.addWidget(self.joint_rdo)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.gridLayout.addWidget(self.groupBox_7, 4, 1, 1, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.create_btn = QtWidgets.QPushButton(self.groupBox)
        self.create_btn.setObjectName("create_btn")
        self.verticalLayout.addWidget(self.create_btn)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(ClusterUI)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scale_rdo = QtWidgets.QRadioButton(self.groupBox_2)
        self.scale_rdo.setChecked(True)
        self.scale_rdo.setObjectName("scale_rdo")
        self.horizontalLayout_4.addWidget(self.scale_rdo)
        self.rot_rdo = QtWidgets.QRadioButton(self.groupBox_2)
        self.rot_rdo.setObjectName("rot_rdo")
        self.horizontalLayout_4.addWidget(self.rot_rdo)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.mirror_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_btn.setEnabled(False)
        self.mirror_btn.setObjectName("mirror_btn")
        self.verticalLayout_2.addWidget(self.mirror_btn)
        self.mirror_shape_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.mirror_shape_btn.setObjectName("mirror_shape_btn")
        self.verticalLayout_2.addWidget(self.mirror_shape_btn)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(ClusterUI)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.shape_mod_cmb = QtWidgets.QComboBox(self.groupBox_3)
        self.shape_mod_cmb.setStyleSheet("QComboBox{background-color:rgb(45,45,45);}")
        self.shape_mod_cmb.setObjectName("shape_mod_cmb")
        self.gridLayout_3.addWidget(self.shape_mod_cmb, 0, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setMinimumSize(QtCore.QSize(100, 0))
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.color_mod_cmb = QtWidgets.QComboBox(self.groupBox_3)
        self.color_mod_cmb.setStyleSheet("QComboBox{background-color:rgb(45,45,45);}")
        self.color_mod_cmb.setObjectName("color_mod_cmb")
        self.gridLayout_3.addWidget(self.color_mod_cmb, 1, 1, 1, 2)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.pivot_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.pivot_btn.setObjectName("pivot_btn")
        self.verticalLayout_3.addWidget(self.pivot_btn)
        self.duplicate_btnb = QtWidgets.QPushButton(self.groupBox_3)
        self.duplicate_btnb.setEnabled(False)
        self.duplicate_btnb.setObjectName("duplicate_btnb")
        self.verticalLayout_3.addWidget(self.duplicate_btnb)
        self.copy_shape_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.copy_shape_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.copy_shape_btn.setObjectName("copy_shape_btn")
        self.verticalLayout_3.addWidget(self.copy_shape_btn)
        self.copy_color_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.copy_color_btn.setObjectName("copy_color_btn")
        self.verticalLayout_3.addWidget(self.copy_color_btn)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(ClusterUI)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.save_shape_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.save_shape_btn.setObjectName("save_shape_btn")
        self.verticalLayout_5.addWidget(self.save_shape_btn)
        self.save_color_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.save_color_btn.setObjectName("save_color_btn")
        self.verticalLayout_5.addWidget(self.save_color_btn)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)

        self.retranslateUi(ClusterUI)
        QtCore.QMetaObject.connectSlotsByName(ClusterUI)
        ClusterUI.setTabOrder(self.name_line, self.create_btn)
        ClusterUI.setTabOrder(self.create_btn, self.mirror_btn)
        ClusterUI.setTabOrder(self.mirror_btn, self.duplicate_btnb)

    def retranslateUi(self, ClusterUI):
        ClusterUI.setWindowTitle(QtCompat.translate("ClusterUI", "Cluster UI", None, -1))
        self.assetLabel_2.setText(QtCompat.translate("ClusterUI", "Control UI", None, -1))
        self.groupBox.setTitle(QtCompat.translate("ClusterUI", "Create New Control", None, -1))
        self.label_8.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Node Type for the control</p></body></html>", None, -1))
        self.label_8.setText(QtCompat.translate("ClusterUI", "Control Node Type", None, -1))
        self.label_10.setText(QtCompat.translate("ClusterUI", "Shape Axis", None, -1))
        self.label_2.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Shape for the new control</p></body></html>", None, -1))
        self.label_2.setText(QtCompat.translate("ClusterUI", "Shape", None, -1))
        self.label_9.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Side prefix for the new control - Either &quot;L_&quot;, &quot;R_&quot;, or &quot;C_&quot;</p></body></html>", None, -1))
        self.label_9.setText(QtCompat.translate("ClusterUI", "Side Token", None, -1))
        self.label.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Name token for the control. If the name of the new control clashes witrh an existing control a unique name will be created.</p></body></html>", None, -1))
        self.label.setText(QtCompat.translate("ClusterUI", "Name Token", None, -1))
        self.label_3.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Shape for the new control</p></body></html>", None, -1))
        self.label_3.setText(QtCompat.translate("ClusterUI", "Color", None, -1))
        self.pivot_chx.setText(QtCompat.translate("ClusterUI", "Create Animatable Pivot", None, -1))
        self.groupBox_5.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Node Type for the control</p></body></html>", None, -1))
        self.X_rdo.setText(QtCompat.translate("ClusterUI", "X", None, -1))
        self.Y_rdo.setText(QtCompat.translate("ClusterUI", "Y", None, -1))
        self.Z_rdo.setText(QtCompat.translate("ClusterUI", "Z", None, -1))
        self.groupBox_6.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Side prefix for the new control - Either &quot;L_&quot;, &quot;R_&quot;, or &quot;C_&quot;</p></body></html>", None, -1))
        self.L_rdo.setText(QtCompat.translate("ClusterUI", "Left", None, -1))
        self.R_rdo.setText(QtCompat.translate("ClusterUI", "Right", None, -1))
        self.C_rdo.setText(QtCompat.translate("ClusterUI", "Center", None, -1))
        self.name_line.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Name token for the control. If the name of the new control clashes witrh an existing control a unique name will be created.</p></body></html>", None, -1))
        self.shape_cmb.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Shape for the new control</p></body></html>", None, -1))
        self.color_cmb.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Shape for the new control</p></body></html>", None, -1))
        self.snap_chx.setText(QtCompat.translate("ClusterUI", "Snap To Current Selection", None, -1))
        self.transform_rdo.setText(QtCompat.translate("ClusterUI", "Transform", None, -1))
        self.joint_rdo.setText(QtCompat.translate("ClusterUI", "Joint", None, -1))
        self.create_btn.setText(QtCompat.translate("ClusterUI", "Create Control", None, -1))
        self.groupBox_2.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Mirror mode for the control. Scale mode wll set a negative scale on the control.</p></body></html>", None, -1))
        self.groupBox_2.setTitle(QtCompat.translate("ClusterUI", "Mirror Selectied Controls", None, -1))
        self.label_7.setToolTip(QtCompat.translate("ClusterUI", "<html><head/><body><p>Mirror mode for the control. Scale mode wll set a negative scale on the control.</p></body></html>", None, -1))
        self.label_7.setText(QtCompat.translate("ClusterUI", "Mirror Mode              ", None, -1))
        self.scale_rdo.setText(QtCompat.translate("ClusterUI", "Scale", None, -1))
        self.rot_rdo.setText(QtCompat.translate("ClusterUI", "Rotation", None, -1))
        self.mirror_btn.setText(QtCompat.translate("ClusterUI", "Mirror Control", None, -1))
        self.mirror_shape_btn.setText(QtCompat.translate("ClusterUI", "Mirror Shape", None, -1))
        self.groupBox_3.setTitle(QtCompat.translate("ClusterUI", "Modify Selectied Controls", None, -1))
        self.label_13.setText(QtCompat.translate("ClusterUI", "Color", None, -1))
        self.label_11.setText(QtCompat.translate("ClusterUI", "Shape", None, -1))
        self.pivot_btn.setText(QtCompat.translate("ClusterUI", "Create Animatable Pivot", None, -1))
        self.duplicate_btnb.setText(QtCompat.translate("ClusterUI", "Duplicate Control", None, -1))
        self.copy_shape_btn.setText(QtCompat.translate("ClusterUI", "Copy Shape", None, -1))
        self.copy_color_btn.setText(QtCompat.translate("ClusterUI", "Copy Color", None, -1))
        self.groupBox_4.setTitle(QtCompat.translate("ClusterUI", "Save To Control Library", None, -1))
        self.save_shape_btn.setText(QtCompat.translate("ClusterUI", "Save New Control Shape Entry", None, -1))
        self.save_color_btn.setText(QtCompat.translate("ClusterUI", "Save New Control Color Entry ( RGB )", None, -1))

