# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/job/comms/pipeline/dev/bhamilton/git/ rigBot/rigBot/gui/export.ui'
#
# Created: Thu Jul 25 17:41:00 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_export_form(object):
    def setupUi(self, export_form):
        export_form.setObjectName("export_form")
        export_form.resize(545, 826)
        export_form.setStatusTip("")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(export_form)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.banner_frame = QtWidgets.QFrame(export_form)
        self.banner_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.banner_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.banner_frame.setStyleSheet("QFrame{background-color: rgb(45, 45, 45);\n"
"color: rgb(230, 230, 230);}")
        self.banner_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.banner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.banner_frame.setObjectName("banner_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.banner_frame)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(4, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_label = QtWidgets.QLabel(self.banner_frame)
        self.icon_label.setMinimumSize(QtCore.QSize(40, 40))
        self.icon_label.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout.addWidget(self.icon_label)
        self.label_19 = QtWidgets.QLabel(self.banner_frame)
        self.label_19.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setIndent(0)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.asset_label = QtWidgets.QLabel(self.banner_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.asset_label.setFont(font)
        self.asset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.asset_label.setObjectName("asset_label")
        self.horizontalLayout.addWidget(self.asset_label)
        self.help_btn = QtWidgets.QPushButton(self.banner_frame)
        self.help_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.help_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.help_btn.setStyleSheet("border-color: rgb(190, 190, 190);")
        self.help_btn.setText("")
        self.help_btn.setFlat(True)
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        self.verticalLayout_12.addWidget(self.banner_frame)
        self.label_6 = QtWidgets.QLabel(export_form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.variant_cmb = QtWidgets.QComboBox(export_form)
        self.variant_cmb.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.variant_cmb.setFont(font)
        self.variant_cmb.setObjectName("variant_cmb")
        self.variant_cmb.addItem("")
        self.verticalLayout_12.addWidget(self.variant_cmb)
        self.frame = QtWidgets.QFrame(export_form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.filter_btn = QtWidgets.QPushButton(self.frame)
        self.filter_btn.setMaximumSize(QtCore.QSize(16777215, 18))
        self.filter_btn.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(175, 175, 175);")
        self.filter_btn.setCheckable(True)
        self.filter_btn.setFlat(False)
        self.filter_btn.setObjectName("filter_btn")
        self.verticalLayout_5.addWidget(self.filter_btn)
        self.filter_frame = QtWidgets.QFrame(self.frame)
        self.filter_frame.setStyleSheet("QFrame{background-color: rgb(60, 60, 60);;}")
        self.filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.filter_layout = QtWidgets.QGridLayout(self.filter_frame)
        self.filter_layout.setObjectName("filter_layout")
        self.all_chx = QtWidgets.QCheckBox(self.filter_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.all_chx.setFont(font)
        self.all_chx.setChecked(True)
        self.all_chx.setObjectName("all_chx")
        self.filter_layout.addWidget(self.all_chx, 0, 0, 1, 1)
        self.bsh_chk = QtWidgets.QCheckBox(self.filter_frame)
        self.bsh_chk.setChecked(True)
        self.bsh_chk.setObjectName("bsh_chk")
        self.filter_layout.addWidget(self.bsh_chk, 1, 0, 1, 1)
        self.cls_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.cls_chx.setChecked(True)
        self.cls_chx.setObjectName("cls_chx")
        self.filter_layout.addWidget(self.cls_chx, 2, 0, 1, 1)
        self.cnct_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.cnct_chx.setChecked(True)
        self.cnct_chx.setObjectName("cnct_chx")
        self.filter_layout.addWidget(self.cnct_chx, 3, 0, 1, 1)
        self.dmush_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.dmush_chx.setChecked(True)
        self.dmush_chx.setObjectName("dmush_chx")
        self.filter_layout.addWidget(self.dmush_chx, 6, 0, 1, 1)
        self.cons_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.cons_chx.setChecked(True)
        self.cons_chx.setObjectName("cons_chx")
        self.filter_layout.addWidget(self.cons_chx, 4, 0, 1, 1)
        self.ffd_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.ffd_chx.setChecked(True)
        self.ffd_chx.setObjectName("ffd_chx")
        self.filter_layout.addWidget(self.ffd_chx, 7, 0, 1, 1)
        self.nld_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.nld_chx.setChecked(True)
        self.nld_chx.setObjectName("nld_chx")
        self.filter_layout.addWidget(self.nld_chx, 1, 1, 1, 1)
        self.pose_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.pose_chx.setChecked(True)
        self.pose_chx.setObjectName("pose_chx")
        self.filter_layout.addWidget(self.pose_chx, 2, 1, 1, 1)
        self.sclp_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.sclp_chx.setChecked(True)
        self.sclp_chx.setObjectName("sclp_chx")
        self.filter_layout.addWidget(self.sclp_chx, 3, 1, 1, 1)
        self.sdk_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.sdk_chx.setChecked(True)
        self.sdk_chx.setObjectName("sdk_chx")
        self.filter_layout.addWidget(self.sdk_chx, 4, 1, 1, 1)
        self.cms_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.cms_chx.setChecked(True)
        self.cms_chx.setObjectName("cms_chx")
        self.filter_layout.addWidget(self.cms_chx, 5, 0, 1, 1)
        self.skn_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.skn_chx.setChecked(True)
        self.skn_chx.setObjectName("skn_chx")
        self.filter_layout.addWidget(self.skn_chx, 5, 1, 1, 1)
        self.attr_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.attr_chx.setChecked(True)
        self.attr_chx.setObjectName("attr_chx")
        self.filter_layout.addWidget(self.attr_chx, 6, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.filter_frame)
        self.verticalLayout_12.addWidget(self.frame)
        self.splitter = QtWidgets.QSplitter(export_form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(4)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.node_list = QtWidgets.QListWidget(self.layoutWidget)
        self.node_list.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.node_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.node_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.node_list.setObjectName("node_list")
        self.verticalLayout_2.addWidget(self.node_list)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.list_btn.setMaximumSize(QtCore.QSize(16777215, 18))
        self.list_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.list_btn.setObjectName("list_btn")
        self.verticalLayout.addWidget(self.list_btn)
        self.list_model_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.list_model_btn.setMaximumSize(QtCore.QSize(16777215, 18))
        self.list_model_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.list_model_btn.setObjectName("list_model_btn")
        self.verticalLayout.addWidget(self.list_model_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.layoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.data_list = QtWidgets.QListWidget(self.layoutWidget_2)
        self.data_list.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.data_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.data_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.data_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.data_list.setObjectName("data_list")
        self.verticalLayout_4.addWidget(self.data_list)
        self.fix_names_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_names_btn.setMaximumSize(QtCore.QSize(16777215, 18))
        self.fix_names_btn.setObjectName("fix_names_btn")
        self.verticalLayout_4.addWidget(self.fix_names_btn)
        self.fix_all_names_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fix_all_names_btn.setMaximumSize(QtCore.QSize(16777215, 18))
        self.fix_all_names_btn.setObjectName("fix_all_names_btn")
        self.verticalLayout_4.addWidget(self.fix_all_names_btn)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_12.addWidget(self.splitter)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stack_btn = QtWidgets.QPushButton(export_form)
        self.stack_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.stack_btn.setObjectName("stack_btn")
        self.gridLayout_2.addWidget(self.stack_btn, 2, 0, 1, 2)
        self.export_btn = QtWidgets.QPushButton(export_form)
        self.export_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.export_btn.setFont(font)
        self.export_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout_2.addWidget(self.export_btn, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 6, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.custom_btn = QtWidgets.QPushButton(export_form)
        self.custom_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.custom_btn.setObjectName("custom_btn")
        self.horizontalLayout_3.addWidget(self.custom_btn)
        self.ncloth_btn = QtWidgets.QPushButton(export_form)
        self.ncloth_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.ncloth_btn.setObjectName("ncloth_btn")
        self.horizontalLayout_3.addWidget(self.ncloth_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ctrls_btn = QtWidgets.QPushButton(export_form)
        self.ctrls_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.ctrls_btn.setObjectName("ctrls_btn")
        self.horizontalLayout_4.addWidget(self.ctrls_btn)
        self.shaders_btn = QtWidgets.QPushButton(export_form)
        self.shaders_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.shaders_btn.setObjectName("shaders_btn")
        self.horizontalLayout_4.addWidget(self.shaders_btn)
        self.sttrs_btn = QtWidgets.QPushButton(export_form)
        self.sttrs_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.sttrs_btn.setObjectName("sttrs_btn")
        self.horizontalLayout_4.addWidget(self.sttrs_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 5, 0, 1, 2)
        self.verticalLayout_12.addLayout(self.gridLayout_2)
        self.verticalLayout_12.setStretch(4, 1)

        self.retranslateUi(export_form)
        QtCore.QMetaObject.connectSlotsByName(export_form)
        export_form.setTabOrder(self.help_btn, self.variant_cmb)
        export_form.setTabOrder(self.variant_cmb, self.list_btn)
        export_form.setTabOrder(self.list_btn, self.list_model_btn)
        export_form.setTabOrder(self.list_model_btn, self.fix_names_btn)
        export_form.setTabOrder(self.fix_names_btn, self.fix_all_names_btn)
        export_form.setTabOrder(self.fix_all_names_btn, self.stack_btn)

    def retranslateUi(self, export_form):
        export_form.setWindowTitle(QtCompat.translate("export_form", "Export Data", None, -1))
        self.label_19.setText(QtCompat.translate("export_form", "Export Data", None, -1))
        self.asset_label.setText(QtCompat.translate("export_form", "Project: Job_name", None, -1))
        self.help_btn.setToolTip(QtCompat.translate("export_form", "Go to documentation.", None, -1))
        self.label_6.setText(QtCompat.translate("export_form", "Rig Variant:", None, -1))
        self.variant_cmb.setToolTip(QtCompat.translate("export_form", "Current rig variant. Set it here to save data for a different vairant.", None, -1))
        self.variant_cmb.setItemText(0, QtCompat.translate("export_form", " Default", None, -1))
        self.filter_btn.setText(QtCompat.translate("export_form", "Data Type Filters", None, -1))
        self.all_chx.setText(QtCompat.translate("export_form", "All Data Types", None, -1))
        self.bsh_chk.setWhatsThis(QtCompat.translate("export_form", "blendShape", None, -1))
        self.bsh_chk.setText(QtCompat.translate("export_form", "BlendShapes", None, -1))
        self.cls_chx.setWhatsThis(QtCompat.translate("export_form", "cluster", None, -1))
        self.cls_chx.setText(QtCompat.translate("export_form", "Clusters", None, -1))
        self.cnct_chx.setWhatsThis(QtCompat.translate("export_form", "connections", None, -1))
        self.cnct_chx.setText(QtCompat.translate("export_form", "Connections", None, -1))
        self.dmush_chx.setWhatsThis(QtCompat.translate("export_form", "deltaMush", None, -1))
        self.dmush_chx.setText(QtCompat.translate("export_form", "DeltaMush", None, -1))
        self.cons_chx.setWhatsThis(QtCompat.translate("export_form", "constraints", None, -1))
        self.cons_chx.setText(QtCompat.translate("export_form", "Constraints", None, -1))
        self.ffd_chx.setWhatsThis(QtCompat.translate("export_form", "lattice", None, -1))
        self.ffd_chx.setText(QtCompat.translate("export_form", "Lattices", None, -1))
        self.nld_chx.setWhatsThis(QtCompat.translate("export_form", "nonLinear", None, -1))
        self.nld_chx.setText(QtCompat.translate("export_form", "Non-Linear", None, -1))
        self.pose_chx.setWhatsThis(QtCompat.translate("export_form", "pose", None, -1))
        self.pose_chx.setText(QtCompat.translate("export_form", "Pose Interpolators", None, -1))
        self.sclp_chx.setWhatsThis(QtCompat.translate("export_form", "sculpt", None, -1))
        self.sclp_chx.setText(QtCompat.translate("export_form", "Sculpt Deformers", None, -1))
        self.sdk_chx.setWhatsThis(QtCompat.translate("export_form", "sdk", None, -1))
        self.sdk_chx.setText(QtCompat.translate("export_form", "Set Driven Keys", None, -1))
        self.cms_chx.setWhatsThis(QtCompat.translate("export_form", "cMuscleSystem", None, -1))
        self.cms_chx.setText(QtCompat.translate("export_form", "cMuscleSystem", None, -1))
        self.skn_chx.setWhatsThis(QtCompat.translate("export_form", "skinCluster", None, -1))
        self.skn_chx.setText(QtCompat.translate("export_form", "SkinClusters", None, -1))
        self.attr_chx.setWhatsThis(QtCompat.translate("export_form", "udAttributes", None, -1))
        self.attr_chx.setText(QtCompat.translate("export_form", "User Defined Attributes", None, -1))
        self.label_4.setText(QtCompat.translate("export_form", "Nodes:", None, -1))
        self.node_list.setToolTip(QtCompat.translate("export_form", "Nodes & geometry to list data for export.", None, -1))
        self.list_btn.setToolTip(QtCompat.translate("export_form", "Add selected nodes to list.", None, -1))
        self.list_btn.setText(QtCompat.translate("export_form", "List Selected Nodes", None, -1))
        self.list_model_btn.setToolTip(QtCompat.translate("export_form", "List selected nodes under model_GRP hierarchy.", None, -1))
        self.list_model_btn.setText(QtCompat.translate("export_form", "List Model_GRP Hierarchy", None, -1))
        self.label_5.setText(QtCompat.translate("export_form", "Deformers & Data:", None, -1))
        self.data_list.setToolTip(QtCompat.translate("export_form", "Deformers & data to select for export.", None, -1))
        self.fix_names_btn.setToolTip(QtCompat.translate("export_form", "Rename selected data and deformers to \"GEO_NAME_\" + the deformer suffix.", None, -1))
        self.fix_names_btn.setText(QtCompat.translate("export_form", "Fix Selected Names", None, -1))
        self.fix_all_names_btn.setToolTip(QtCompat.translate("export_form", "Rename all data and deformers in list to \"GEO_NAME_\" + the deformer suffix.", None, -1))
        self.fix_all_names_btn.setText(QtCompat.translate("export_form", "Fix All Names In List", None, -1))
        self.stack_btn.setToolTip(QtCompat.translate("export_form", "Export selected defomrer stack to asset / data / variant folder. (Right-click for more options.)", None, -1))
        self.stack_btn.setText(QtCompat.translate("export_form", "Export Deformer Stack For Selected Nodes", None, -1))
        self.export_btn.setToolTip(QtCompat.translate("export_form", "Export selected data to asset / data / variant folder. (Right-click for more options.)", None, -1))
        self.export_btn.setText(QtCompat.translate("export_form", "Export Selected Data", None, -1))
        self.custom_btn.setToolTip(QtCompat.translate("export_form", "Export all custom rigging to asset / data / variant folder. (Right-click for more options.)", None, -1))
        self.custom_btn.setText(QtCompat.translate("export_form", "Export Custom Rigging", None, -1))
        self.ncloth_btn.setToolTip(QtCompat.translate("export_form", "Export all keyable attribute states and values to asset / data / variant folder. (Right-click for more options.)", None, -1))
        self.ncloth_btn.setText(QtCompat.translate("export_form", "Export nCloth", None, -1))
        self.ctrls_btn.setToolTip(QtCompat.translate("export_form", "Export all control shapes data to asset / data / variant folder. (Right-click for more options.)", None, -1))
        self.ctrls_btn.setText(QtCompat.translate("export_form", "Export Ctrl Shapes", None, -1))
        self.shaders_btn.setToolTip(QtCompat.translate("export_form", "Export all control shapes data to asset / data / variant folder. (Right-click for more options.)", None, -1))
        self.shaders_btn.setText(QtCompat.translate("export_form", "Export Anim Shaders", None, -1))
        self.sttrs_btn.setToolTip(QtCompat.translate("export_form", "Export all keyable attribute states and values to asset / data / variant folder. (Right-click for more options.)", None, -1))
        self.sttrs_btn.setText(QtCompat.translate("export_form", "Export Keyable Attributes", None, -1))

