# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/job/comms/pipeline/dev/bhamilton/git/ rigBot/rigBot/gui/loadData.ui'
#
# Created: Thu Jul 25 18:05:43 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(342, 656)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.banner_frame = QtWidgets.QFrame(Form)
        self.banner_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.banner_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.banner_frame.setStyleSheet("QFrame{background-color: rgb(45, 45, 45);\n"
"color: rgb(230, 230, 230);}")
        self.banner_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.banner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.banner_frame.setObjectName("banner_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.banner_frame)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(4, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_19 = QtWidgets.QLabel(self.banner_frame)
        self.label_19.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setIndent(0)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.asset_label = QtWidgets.QLabel(self.banner_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.asset_label.setFont(font)
        self.asset_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.asset_label.setObjectName("asset_label")
        self.horizontalLayout.addWidget(self.asset_label)
        self.verticalLayout.addWidget(self.banner_frame)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.variant_cmb = QtWidgets.QComboBox(Form)
        self.variant_cmb.setEnabled(False)
        self.variant_cmb.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.variant_cmb.setFont(font)
        self.variant_cmb.setObjectName("variant_cmb")
        self.variant_cmb.addItem("")
        self.verticalLayout.addWidget(self.variant_cmb)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.filter_btn = QtWidgets.QPushButton(self.frame)
        self.filter_btn.setEnabled(False)
        self.filter_btn.setMaximumSize(QtCore.QSize(16777215, 18))
        self.filter_btn.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(175, 175, 175);")
        self.filter_btn.setCheckable(True)
        self.filter_btn.setFlat(False)
        self.filter_btn.setObjectName("filter_btn")
        self.verticalLayout_5.addWidget(self.filter_btn)
        self.filter_frame = QtWidgets.QFrame(self.frame)
        self.filter_frame.setStyleSheet("QFrame{background-color: rgb(60, 60, 60);;}")
        self.filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.filter_layout = QtWidgets.QGridLayout(self.filter_frame)
        self.filter_layout.setObjectName("filter_layout")
        self.all_chx = QtWidgets.QCheckBox(self.filter_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.all_chx.setFont(font)
        self.all_chx.setChecked(True)
        self.all_chx.setObjectName("all_chx")
        self.filter_layout.addWidget(self.all_chx, 0, 0, 1, 1)
        self.bsh_chk = QtWidgets.QCheckBox(self.filter_frame)
        self.bsh_chk.setChecked(True)
        self.bsh_chk.setObjectName("bsh_chk")
        self.filter_layout.addWidget(self.bsh_chk, 3, 0, 1, 1)
        self.cls_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.cls_chx.setChecked(True)
        self.cls_chx.setObjectName("cls_chx")
        self.filter_layout.addWidget(self.cls_chx, 4, 0, 1, 1)
        self.cnct_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.cnct_chx.setChecked(True)
        self.cnct_chx.setObjectName("cnct_chx")
        self.filter_layout.addWidget(self.cnct_chx, 6, 0, 1, 1)
        self.cons_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.cons_chx.setChecked(True)
        self.cons_chx.setObjectName("cons_chx")
        self.filter_layout.addWidget(self.cons_chx, 7, 0, 1, 1)
        self.custom_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.custom_chx.setChecked(True)
        self.custom_chx.setObjectName("custom_chx")
        self.filter_layout.addWidget(self.custom_chx, 9, 0, 1, 1)
        self.shd_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.shd_chx.setChecked(True)
        self.shd_chx.setObjectName("shd_chx")
        self.filter_layout.addWidget(self.shd_chx, 1, 0, 1, 1)
        self.ctrls_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.ctrls_chx.setChecked(True)
        self.ctrls_chx.setObjectName("ctrls_chx")
        self.filter_layout.addWidget(self.ctrls_chx, 8, 0, 1, 1)
        self.dstack_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.dstack_chx.setChecked(True)
        self.dstack_chx.setObjectName("dstack_chx")
        self.filter_layout.addWidget(self.dstack_chx, 10, 0, 1, 1)
        self.kattr_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.kattr_chx.setChecked(True)
        self.kattr_chx.setObjectName("kattr_chx")
        self.filter_layout.addWidget(self.kattr_chx, 2, 0, 1, 1)
        self.nld_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.nld_chx.setChecked(True)
        self.nld_chx.setObjectName("nld_chx")
        self.filter_layout.addWidget(self.nld_chx, 4, 1, 1, 1)
        self.ncloth_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.ncloth_chx.setChecked(True)
        self.ncloth_chx.setObjectName("ncloth_chx")
        self.filter_layout.addWidget(self.ncloth_chx, 3, 1, 1, 1)
        self.ffd_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.ffd_chx.setChecked(True)
        self.ffd_chx.setObjectName("ffd_chx")
        self.filter_layout.addWidget(self.ffd_chx, 2, 1, 1, 1)
        self.dmush_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.dmush_chx.setChecked(True)
        self.dmush_chx.setObjectName("dmush_chx")
        self.filter_layout.addWidget(self.dmush_chx, 1, 1, 1, 1)
        self.cnct_chx_2 = QtWidgets.QCheckBox(self.filter_frame)
        self.cnct_chx_2.setChecked(True)
        self.cnct_chx_2.setObjectName("cnct_chx_2")
        self.filter_layout.addWidget(self.cnct_chx_2, 5, 0, 1, 1)
        self.pose_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.pose_chx.setChecked(True)
        self.pose_chx.setObjectName("pose_chx")
        self.filter_layout.addWidget(self.pose_chx, 5, 1, 1, 1)
        self.sclp_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.sclp_chx.setChecked(True)
        self.sclp_chx.setObjectName("sclp_chx")
        self.filter_layout.addWidget(self.sclp_chx, 6, 1, 1, 1)
        self.sdk_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.sdk_chx.setChecked(True)
        self.sdk_chx.setObjectName("sdk_chx")
        self.filter_layout.addWidget(self.sdk_chx, 7, 1, 1, 1)
        self.skn_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.skn_chx.setChecked(True)
        self.skn_chx.setObjectName("skn_chx")
        self.filter_layout.addWidget(self.skn_chx, 8, 1, 1, 1)
        self.attr_chx = QtWidgets.QCheckBox(self.filter_frame)
        self.attr_chx.setChecked(True)
        self.attr_chx.setObjectName("attr_chx")
        self.filter_layout.addWidget(self.attr_chx, 9, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.filter_frame)
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.none_frame_2 = QtWidgets.QFrame(Form)
        self.none_frame_2.setMinimumSize(QtCore.QSize(245, 0))
        self.none_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.none_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.none_frame_2.setObjectName("none_frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.none_frame_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.part_label_3 = QtWidgets.QLabel(self.none_frame_2)
        self.part_label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.part_label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.part_label_3.setFont(font)
        self.part_label_3.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.part_label_3.setLineWidth(0)
        self.part_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.part_label_3.setIndent(9)
        self.part_label_3.setObjectName("part_label_3")
        self.verticalLayout_13.addWidget(self.part_label_3)
        self.options_grp_3 = QtWidgets.QGroupBox(self.none_frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.options_grp_3.setFont(font)
        self.options_grp_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.options_grp_3.setTitle("")
        self.options_grp_3.setFlat(True)
        self.options_grp_3.setObjectName("options_grp_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.options_grp_3)
        self.verticalLayout_2.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.options_grp_3)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.vert_rdo = QtWidgets.QRadioButton(self.groupBox)
        self.vert_rdo.setChecked(True)
        self.vert_rdo.setObjectName("vert_rdo")
        self.gridLayout.addWidget(self.vert_rdo, 1, 1, 1, 1)
        self.cpoint_rdo = QtWidgets.QRadioButton(self.groupBox)
        self.cpoint_rdo.setObjectName("cpoint_rdo")
        self.gridLayout.addWidget(self.cpoint_rdo, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.remap_chx = QtWidgets.QCheckBox(self.options_grp_3)
        self.remap_chx.setObjectName("remap_chx")
        self.verticalLayout_2.addWidget(self.remap_chx)
        self.verticalLayout_13.addWidget(self.options_grp_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_13)
        self.verticalLayout.addWidget(self.none_frame_2)
        self.import_btn = QtWidgets.QPushButton(Form)
        self.import_btn.setObjectName("import_btn")
        self.verticalLayout.addWidget(self.import_btn)
        self.import_all_btn = QtWidgets.QPushButton(Form)
        self.import_all_btn.setObjectName("import_all_btn")
        self.verticalLayout.addWidget(self.import_all_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtCompat.translate("Form", "Load Data Util", None, -1))
        self.label_19.setText(QtCompat.translate("Form", " Load Data", None, -1))
        self.asset_label.setText(QtCompat.translate("Form", "Asset: ", None, -1))
        self.label_6.setText(QtCompat.translate("Form", "Rig Variant:", None, -1))
        self.variant_cmb.setToolTip(QtCompat.translate("Form", "Current rig variant. ", None, -1))
        self.variant_cmb.setItemText(0, QtCompat.translate("Form", " Default", None, -1))
        self.filter_btn.setText(QtCompat.translate("Form", "Data Type Filters", None, -1))
        self.all_chx.setText(QtCompat.translate("Form", "All Data Types", None, -1))
        self.bsh_chk.setWhatsThis(QtCompat.translate("Form", "blendShape", None, -1))
        self.bsh_chk.setText(QtCompat.translate("Form", "BlendShapes", None, -1))
        self.cls_chx.setWhatsThis(QtCompat.translate("Form", "cluster", None, -1))
        self.cls_chx.setText(QtCompat.translate("Form", "Clusters", None, -1))
        self.cnct_chx.setWhatsThis(QtCompat.translate("Form", "connections", None, -1))
        self.cnct_chx.setText(QtCompat.translate("Form", "Connections", None, -1))
        self.cons_chx.setWhatsThis(QtCompat.translate("Form", "constraints", None, -1))
        self.cons_chx.setText(QtCompat.translate("Form", "Constraints", None, -1))
        self.custom_chx.setWhatsThis(QtCompat.translate("Form", "customRig", None, -1))
        self.custom_chx.setText(QtCompat.translate("Form", "Custom Rigging", None, -1))
        self.shd_chx.setWhatsThis(QtCompat.translate("Form", "shaders", None, -1))
        self.shd_chx.setText(QtCompat.translate("Form", "Anim Shaders", None, -1))
        self.ctrls_chx.setWhatsThis(QtCompat.translate("Form", "controlShapes", None, -1))
        self.ctrls_chx.setText(QtCompat.translate("Form", "Control Shapes", None, -1))
        self.dstack_chx.setWhatsThis(QtCompat.translate("Form", "stack", None, -1))
        self.dstack_chx.setText(QtCompat.translate("Form", "Deformer Stack", None, -1))
        self.kattr_chx.setWhatsThis(QtCompat.translate("Form", "kAttributes", None, -1))
        self.kattr_chx.setText(QtCompat.translate("Form", "Attributes Settings", None, -1))
        self.nld_chx.setWhatsThis(QtCompat.translate("Form", "nonLinear", None, -1))
        self.nld_chx.setText(QtCompat.translate("Form", "Non-Linear", None, -1))
        self.ncloth_chx.setWhatsThis(QtCompat.translate("Form", "nCloth", None, -1))
        self.ncloth_chx.setText(QtCompat.translate("Form", "nCloth", None, -1))
        self.ffd_chx.setWhatsThis(QtCompat.translate("Form", "lattice", None, -1))
        self.ffd_chx.setText(QtCompat.translate("Form", "Lattices", None, -1))
        self.dmush_chx.setWhatsThis(QtCompat.translate("Form", "deltaMush", None, -1))
        self.dmush_chx.setText(QtCompat.translate("Form", "DeltaMush", None, -1))
        self.cnct_chx_2.setWhatsThis(QtCompat.translate("Form", "cMuscleSystem", None, -1))
        self.cnct_chx_2.setText(QtCompat.translate("Form", "cMuscleSystem", None, -1))
        self.pose_chx.setWhatsThis(QtCompat.translate("Form", "pose", None, -1))
        self.pose_chx.setText(QtCompat.translate("Form", "Pose Interpolators", None, -1))
        self.sclp_chx.setWhatsThis(QtCompat.translate("Form", "sculpt", None, -1))
        self.sclp_chx.setText(QtCompat.translate("Form", "Sculpt Deformers", None, -1))
        self.sdk_chx.setWhatsThis(QtCompat.translate("Form", "sdk", None, -1))
        self.sdk_chx.setText(QtCompat.translate("Form", "Set Driven Keys", None, -1))
        self.skn_chx.setWhatsThis(QtCompat.translate("Form", "skinCluster", None, -1))
        self.skn_chx.setText(QtCompat.translate("Form", "SkinClusters", None, -1))
        self.attr_chx.setWhatsThis(QtCompat.translate("Form", "udAttributes", None, -1))
        self.attr_chx.setText(QtCompat.translate("Form", "User Defined Attributes", None, -1))
        self.part_label_3.setText(QtCompat.translate("Form", "Load Options", None, -1))
        self.groupBox.setToolTip(QtCompat.translate("Form", "Load data based on vertex ID or closest point. \n"
"Use closest point if your vert count or vert order has changed.", None, -1))
        self.vert_rdo.setText(QtCompat.translate("Form", "Vertex ID", None, -1))
        self.cpoint_rdo.setText(QtCompat.translate("Form", "Closest Point On Mesh", None, -1))
        self.label_2.setText(QtCompat.translate("Form", "Surface Association:", None, -1))
        self.remap_chx.setToolTip(QtCompat.translate("Form", "Remap node names from one to another. \n"
"Use this if geo names or joint names have changed or no longer exist.", None, -1))
        self.remap_chx.setText(QtCompat.translate("Form", "Remap Node Names (One data file at a time)", None, -1))
        self.import_btn.setToolTip(QtCompat.translate("Form", "Browse for specifc data files to load. ", None, -1))
        self.import_btn.setText(QtCompat.translate("Form", "Browse && Load Data", None, -1))
        self.import_all_btn.setToolTip(QtCompat.translate("Form", "Load all data modules for the given data types for the currently set rig variant. ", None, -1))
        self.import_all_btn.setText(QtCompat.translate("Form", "Load All Variant Data", None, -1))

