# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/job/comms/pipeline/dev/bhamilton/git/ rigBot/rigBot/gui/main.ui'
#
# Created: Mon Jun 24 15:54:34 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_asset_env_form(object):
    def setupUi(self, asset_env_form):
        asset_env_form.setObjectName("asset_env_form")
        asset_env_form.resize(528, 1279)
        asset_env_form.setStatusTip("")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(asset_env_form)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(asset_env_form)
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.banner_frame = QtWidgets.QFrame(self.tab)
        self.banner_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.banner_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.banner_frame.setStyleSheet("QFrame{background-color: rgb(45, 45, 45);\n"
"color: rgb(230, 230, 230);}")
        self.banner_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.banner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.banner_frame.setObjectName("banner_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.banner_frame)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(4, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_label = QtWidgets.QLabel(self.banner_frame)
        self.icon_label.setMinimumSize(QtCore.QSize(40, 40))
        self.icon_label.setMaximumSize(QtCore.QSize(40, 40))
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout.addWidget(self.icon_label)
        self.label_19 = QtWidgets.QLabel(self.banner_frame)
        self.label_19.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setIndent(0)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.job_label = QtWidgets.QLabel(self.banner_frame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.job_label.setFont(font)
        self.job_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.job_label.setStyleSheet("QToolTip{background-color: rgb(255, 255, 127);}\n"
"")
        self.job_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.job_label.setObjectName("job_label")
        self.horizontalLayout.addWidget(self.job_label)
        self.set_project_cmb = QtWidgets.QComboBox(self.banner_frame)
        self.set_project_cmb.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.set_project_cmb.setStyleSheet("QComboBox{background-color: rgb(65, 65, 65);\n"
"color: rgb(230, 230, 230);}\n"
"")
        self.set_project_cmb.setObjectName("set_project_cmb")
        self.horizontalLayout.addWidget(self.set_project_cmb)
        self.help_btn = QtWidgets.QPushButton(self.banner_frame)
        self.help_btn.setMinimumSize(QtCore.QSize(24, 24))
        self.help_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.help_btn.setStyleSheet("QPushButton{border-color: rgb(190, 190, 190);}")
        self.help_btn.setText("")
        self.help_btn.setFlat(True)
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        self.verticalLayout.addWidget(self.banner_frame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(9)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.asset_frame = QtWidgets.QFrame(self.tab)
        self.asset_frame.setMinimumSize(QtCore.QSize(248, 0))
        self.asset_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.asset_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.asset_frame.setObjectName("asset_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.asset_frame)
        self.verticalLayout_3.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.info_frame = QtWidgets.QFrame(self.asset_frame)
        self.info_frame.setMinimumSize(QtCore.QSize(245, 0))
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.info_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.asset_label = QtWidgets.QLabel(self.info_frame)
        self.asset_label.setMinimumSize(QtCore.QSize(0, 25))
        self.asset_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.asset_label.setFont(font)
        self.asset_label.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.asset_label.setLineWidth(0)
        self.asset_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.asset_label.setIndent(9)
        self.asset_label.setObjectName("asset_label")
        self.verticalLayout_5.addWidget(self.asset_label)
        self.icon_grp = QtWidgets.QGroupBox(self.info_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.icon_grp.setFont(font)
        self.icon_grp.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.icon_grp.setTitle("")
        self.icon_grp.setFlat(True)
        self.icon_grp.setObjectName("icon_grp")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.icon_grp)
        self.verticalLayout_13.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.icon_grid = QtWidgets.QGridLayout()
        self.icon_grid.setVerticalSpacing(0)
        self.icon_grid.setObjectName("icon_grid")
        self.thumb_label = QtWidgets.QLabel(self.icon_grp)
        self.thumb_label.setMinimumSize(QtCore.QSize(213, 120))
        self.thumb_label.setMaximumSize(QtCore.QSize(213, 120))
        self.thumb_label.setText("")
        self.thumb_label.setAlignment(QtCore.Qt.AlignCenter)
        self.thumb_label.setObjectName("thumb_label")
        self.icon_grid.addWidget(self.thumb_label, 0, 0, 1, 1)
        self.verticalLayout_13.addLayout(self.icon_grid)
        self.icon_btn_2 = QtWidgets.QPushButton(self.icon_grp)
        self.icon_btn_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.icon_btn_2.setObjectName("icon_btn_2")
        self.verticalLayout_13.addWidget(self.icon_btn_2)
        self.verticalLayout_5.addWidget(self.icon_grp)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.variant_grp = QtWidgets.QGroupBox(self.info_frame)
        self.variant_grp.setObjectName("variant_grp")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.variant_grp)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.variant_label = QtWidgets.QLabel(self.variant_grp)
        self.variant_label.setObjectName("variant_label")
        self.verticalLayout_9.addWidget(self.variant_label)
        self.variant_btn = QtWidgets.QPushButton(self.variant_grp)
        self.variant_btn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.variant_btn.setObjectName("variant_btn")
        self.verticalLayout_9.addWidget(self.variant_btn)
        self.verticalLayout_2.addWidget(self.variant_grp)
        self.inherit_grp = QtWidgets.QGroupBox(self.info_frame)
        self.inherit_grp.setObjectName("inherit_grp")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.inherit_grp)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.inherit_label = QtWidgets.QLabel(self.inherit_grp)
        self.inherit_label.setText("")
        self.inherit_label.setObjectName("inherit_label")
        self.verticalLayout_10.addWidget(self.inherit_label)
        self.inherit_btn = QtWidgets.QPushButton(self.inherit_grp)
        self.inherit_btn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.inherit_btn.setObjectName("inherit_btn")
        self.verticalLayout_10.addWidget(self.inherit_btn)
        self.verticalLayout_2.addWidget(self.inherit_grp)
        self.creation_grp = QtWidgets.QGroupBox(self.info_frame)
        self.creation_grp.setObjectName("creation_grp")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.creation_grp)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.creation_grid = QtWidgets.QGridLayout()
        self.creation_grid.setObjectName("creation_grid")
        self.create_date_text_label = QtWidgets.QLabel(self.creation_grp)
        self.create_date_text_label.setObjectName("create_date_text_label")
        self.creation_grid.addWidget(self.create_date_text_label, 0, 0, 1, 1)
        self.create_date_label = QtWidgets.QLabel(self.creation_grp)
        self.create_date_label.setObjectName("create_date_label")
        self.creation_grid.addWidget(self.create_date_label, 0, 1, 1, 1)
        self.modified_by_label = QtWidgets.QLabel(self.creation_grp)
        self.modified_by_label.setObjectName("modified_by_label")
        self.creation_grid.addWidget(self.modified_by_label, 2, 1, 1, 1)
        self.modified_by_text_label = QtWidgets.QLabel(self.creation_grp)
        self.modified_by_text_label.setObjectName("modified_by_text_label")
        self.creation_grid.addWidget(self.modified_by_text_label, 2, 0, 1, 1)
        self.modified_text_label = QtWidgets.QLabel(self.creation_grp)
        self.modified_text_label.setObjectName("modified_text_label")
        self.creation_grid.addWidget(self.modified_text_label, 1, 0, 1, 1)
        self.modified_label = QtWidgets.QLabel(self.creation_grp)
        self.modified_label.setObjectName("modified_label")
        self.creation_grid.addWidget(self.modified_label, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.creation_grid)
        self.verticalLayout_2.addWidget(self.creation_grp)
        self.verticalLayout_3.addWidget(self.info_frame)
        self.make_files_frame = QtWidgets.QFrame(self.asset_frame)
        self.make_files_frame.setMinimumSize(QtCore.QSize(245, 0))
        self.make_files_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.make_files_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.make_files_frame.setObjectName("make_files_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.make_files_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.asset_label_3 = QtWidgets.QLabel(self.make_files_frame)
        self.asset_label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.asset_label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.asset_label_3.setFont(font)
        self.asset_label_3.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.asset_label_3.setLineWidth(0)
        self.asset_label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.asset_label_3.setIndent(9)
        self.asset_label_3.setObjectName("asset_label_3")
        self.verticalLayout_6.addWidget(self.asset_label_3)
        self.create_grp_3 = QtWidgets.QGroupBox(self.make_files_frame)
        self.create_grp_3.setTitle("")
        self.create_grp_3.setObjectName("create_grp_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.create_grp_3)
        self.verticalLayout_8.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.create_grp_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.label_22 = QtWidgets.QLabel(self.create_grp_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.create_grp_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_8.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.create_grp_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_8.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.create_grp_3)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_8.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.create_grp_3)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.create_grp_3)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_8.addWidget(self.label_27)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem)
        self.create_files_btn = QtWidgets.QPushButton(self.create_grp_3)
        self.create_files_btn.setObjectName("create_files_btn")
        self.verticalLayout_8.addWidget(self.create_files_btn)
        self.verticalLayout_6.addWidget(self.create_grp_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addWidget(self.make_files_frame)
        self.make_files_frame_2 = QtWidgets.QFrame(self.asset_frame)
        self.make_files_frame_2.setMinimumSize(QtCore.QSize(245, 0))
        self.make_files_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.make_files_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.make_files_frame_2.setObjectName("make_files_frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.make_files_frame_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.asset_label_4 = QtWidgets.QLabel(self.make_files_frame_2)
        self.asset_label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.asset_label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.asset_label_4.setFont(font)
        self.asset_label_4.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.asset_label_4.setLineWidth(0)
        self.asset_label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.asset_label_4.setIndent(9)
        self.asset_label_4.setObjectName("asset_label_4")
        self.verticalLayout_14.addWidget(self.asset_label_4)
        self.create_grp_4 = QtWidgets.QGroupBox(self.make_files_frame_2)
        self.create_grp_4.setTitle("")
        self.create_grp_4.setObjectName("create_grp_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.create_grp_4)
        self.verticalLayout_15.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_28 = QtWidgets.QLabel(self.create_grp_4)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_15.addWidget(self.label_28)
        self.verticalLayout_14.addWidget(self.create_grp_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_3.addWidget(self.make_files_frame_2)
        self.make_files_frame_3 = QtWidgets.QFrame(self.asset_frame)
        self.make_files_frame_3.setMinimumSize(QtCore.QSize(245, 0))
        self.make_files_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.make_files_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.make_files_frame_3.setObjectName("make_files_frame_3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.make_files_frame_3)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.asset_label_6 = QtWidgets.QLabel(self.make_files_frame_3)
        self.asset_label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.asset_label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.asset_label_6.setFont(font)
        self.asset_label_6.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.asset_label_6.setLineWidth(0)
        self.asset_label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.asset_label_6.setIndent(9)
        self.asset_label_6.setObjectName("asset_label_6")
        self.verticalLayout_19.addWidget(self.asset_label_6)
        self.create_grp_6 = QtWidgets.QGroupBox(self.make_files_frame_3)
        self.create_grp_6.setTitle("")
        self.create_grp_6.setObjectName("create_grp_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.create_grp_6)
        self.verticalLayout_20.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_29 = QtWidgets.QLabel(self.create_grp_6)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_20.addWidget(self.label_29)
        self.comboBox = QtWidgets.QComboBox(self.create_grp_6)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_20.addWidget(self.comboBox)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_30 = QtWidgets.QLabel(self.create_grp_6)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_16.addWidget(self.label_30)
        self.lineEdit = QtWidgets.QLineEdit(self.create_grp_6)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_16.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.create_grp_6)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 15))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_16.addWidget(self.pushButton)
        self.verticalLayout_20.addLayout(self.verticalLayout_16)
        self.verticalLayout_19.addWidget(self.create_grp_6)
        self.verticalLayout_17.addLayout(self.verticalLayout_19)
        self.verticalLayout_3.addWidget(self.make_files_frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(245, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 113, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.gridLayout.addWidget(self.asset_frame, 1, 1, 1, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setStyleSheet("QFrame{background-color: rgb(55, 55, 55);}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.alpha_btn_3 = QtWidgets.QPushButton(self.frame_2)
        self.alpha_btn_3.setMaximumSize(QtCore.QSize(60, 20))
        self.alpha_btn_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.alpha_btn_3.setObjectName("alpha_btn_3")
        self.horizontalLayout_5.addWidget(self.alpha_btn_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 0, 1, 2)
        self.verticalLayout_18.addWidget(self.frame_2)
        self.asset_list = QtWidgets.QListWidget(self.tab)
        self.asset_list.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.asset_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.asset_list.setObjectName("asset_list")
        self.verticalLayout_18.addWidget(self.asset_list)
        self.gridLayout.addLayout(self.verticalLayout_18, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_12.addWidget(self.tabWidget)
        self.frame = QtWidgets.QFrame(asset_env_form)
        self.frame.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.rigbuild_path_line = QtWidgets.QLineEdit(self.frame)
        self.rigbuild_path_line.setToolTip("")
        self.rigbuild_path_line.setStyleSheet("background-color: rgb(55, 55, 55);\n"
"color: rgb(150, 150, 150);")
        self.rigbuild_path_line.setFrame(False)
        self.rigbuild_path_line.setReadOnly(True)
        self.rigbuild_path_line.setObjectName("rigbuild_path_line")
        self.horizontalLayout_2.addWidget(self.rigbuild_path_line)
        self.browse_btn = QtWidgets.QPushButton(self.frame)
        self.browse_btn.setMinimumSize(QtCore.QSize(35, 20))
        self.browse_btn.setMaximumSize(QtCore.QSize(35, 20))
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_2.addWidget(self.browse_btn)
        self.verticalLayout_12.addWidget(self.frame)

        self.retranslateUi(asset_env_form)
        QtCore.QMetaObject.connectSlotsByName(asset_env_form)
        asset_env_form.setTabOrder(self.tabWidget, self.set_project_cmb)
        asset_env_form.setTabOrder(self.set_project_cmb, self.help_btn)
        asset_env_form.setTabOrder(self.help_btn, self.icon_btn_2)
        asset_env_form.setTabOrder(self.icon_btn_2, self.variant_btn)
        asset_env_form.setTabOrder(self.variant_btn, self.inherit_btn)
        asset_env_form.setTabOrder(self.inherit_btn, self.create_files_btn)
        asset_env_form.setTabOrder(self.create_files_btn, self.rigbuild_path_line)
        asset_env_form.setTabOrder(self.rigbuild_path_line, self.browse_btn)

    def retranslateUi(self, asset_env_form):
        asset_env_form.setWindowTitle(QtCompat.translate("asset_env_form", "Asset Environment", None, -1))
        self.label_19.setText(QtCompat.translate("asset_env_form", "Asset Env", None, -1))
        self.job_label.setText(QtCompat.translate("asset_env_form", "Project: Job_name", None, -1))
        self.help_btn.setToolTip(QtCompat.translate("asset_env_form", "Go to documentation.", None, -1))
        self.label_3.setText(QtCompat.translate("asset_env_form", "Current Asset:", None, -1))
        self.label_4.setText(QtCompat.translate("asset_env_form", "All Assets:", None, -1))
        self.asset_label.setText(QtCompat.translate("asset_env_form", "Bunny", None, -1))
        self.icon_btn_2.setToolTip(QtCompat.translate("asset_env_form", "Take a screenshot to use as an asset thumbnail.", None, -1))
        self.icon_btn_2.setText(QtCompat.translate("asset_env_form", "Take Thumbnail Snapshot", None, -1))
        self.variant_grp.setTitle(QtCompat.translate("asset_env_form", "Rig Variants:", None, -1))
        self.variant_label.setText(QtCompat.translate("asset_env_form", "TextLabel", None, -1))
        self.variant_btn.setToolTip(QtCompat.translate("asset_env_form", "Add a rig variant. ", None, -1))
        self.variant_btn.setText(QtCompat.translate("asset_env_form", "Add Rig Variants", None, -1))
        self.inherit_grp.setTitle(QtCompat.translate("asset_env_form", "Inherits Asset:", None, -1))
        self.inherit_btn.setToolTip(QtCompat.translate("asset_env_form", "Set another asset to inherit scripts and / or guides files from. ", None, -1))
        self.inherit_btn.setText(QtCompat.translate("asset_env_form", "Set Inheritance", None, -1))
        self.creation_grp.setTitle(QtCompat.translate("asset_env_form", "Creation Info:", None, -1))
        self.create_date_text_label.setText(QtCompat.translate("asset_env_form", "Created On:", None, -1))
        self.create_date_label.setText(QtCompat.translate("asset_env_form", "06/01/2018", None, -1))
        self.modified_by_label.setText(QtCompat.translate("asset_env_form", "bhamilton", None, -1))
        self.modified_by_text_label.setText(QtCompat.translate("asset_env_form", "Last Modified By:", None, -1))
        self.modified_text_label.setText(QtCompat.translate("asset_env_form", "Last Modified:", None, -1))
        self.modified_label.setText(QtCompat.translate("asset_env_form", "08/07/2018", None, -1))
        self.asset_label_3.setText(QtCompat.translate("asset_env_form", "No Rig Files Available", None, -1))
        self.label_18.setText(QtCompat.translate("asset_env_form", "Rig files do not exist for this asset.\n"
"Do you want to create them on disk?", None, -1))
        self.label_22.setText(QtCompat.translate("asset_env_form", "Files to be created: ", None, -1))
        self.label_23.setText(QtCompat.translate("asset_env_form", "    • rigbuild (directory)", None, -1))
        self.label_24.setText(QtCompat.translate("asset_env_form", "    • data (directory)", None, -1))
        self.label_25.setText(QtCompat.translate("asset_env_form", "    • assetInfo.json", None, -1))
        self.label_26.setText(QtCompat.translate("asset_env_form", "    • asset_rigAll.py", None, -1))
        self.label_27.setText(QtCompat.translate("asset_env_form", "    • asset_custom.py", None, -1))
        self.create_files_btn.setToolTip(QtCompat.translate("asset_env_form", "Create rigbuild directories and files on disk. ", None, -1))
        self.create_files_btn.setText(QtCompat.translate("asset_env_form", "Create Rig Files On Disk", None, -1))
        self.asset_label_4.setText(QtCompat.translate("asset_env_form", "Asset Not Set", None, -1))
        self.label_28.setText(QtCompat.translate("asset_env_form", "Choose an asset to\n"
"set your environment ", None, -1))
        self.asset_label_6.setText(QtCompat.translate("asset_env_form", "Sandbox Mode", None, -1))
        self.label_29.setText(QtCompat.translate("asset_env_form", "Available only for assets that have a\n"
"rigbuild folder managed through GIT. ", None, -1))
        self.comboBox.setItemText(0, QtCompat.translate("asset_env_form", "User Sandbox ( If available )", None, -1))
        self.comboBox.setItemText(1, QtCompat.translate("asset_env_form", "Show Common", None, -1))
        self.label_30.setText(QtCompat.translate("asset_env_form", "Sandbox User:", None, -1))
        self.pushButton.setText(QtCompat.translate("asset_env_form", "Reset To Self", None, -1))
        self.label_6.setText(QtCompat.translate("asset_env_form", "Filter:", None, -1))
        self.alpha_btn_3.setToolTip(QtCompat.translate("asset_env_form", "Build only selected steps in the list", None, -1))
        self.alpha_btn_3.setText(QtCompat.translate("asset_env_form", "Clear", None, -1))
        self.asset_list.setToolTip(QtCompat.translate("asset_env_form", "List of available assets on this job.", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtCompat.translate("asset_env_form", "Asset Env", None, -1))
        self.label.setToolTip(QtCompat.translate("asset_env_form", "Path to this assets\' rigbuild folder.", None, -1))
        self.label.setText(QtCompat.translate("asset_env_form", "Rigbuild Path", None, -1))
        self.browse_btn.setToolTip(QtCompat.translate("asset_env_form", "Open a file browser window to this rigbuild path.", None, -1))
        self.browse_btn.setText(QtCompat.translate("asset_env_form", "...", None, -1))

