# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/job/comms/pipeline/dev/bhamilton/git/ rigBot/rigBot/gui/partsLibrary.ui'
#
# Created: Mon Jun 24 16:11:16 2019
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_PartsLibrary(object):
    def setupUi(self, PartsLibrary):
        PartsLibrary.setObjectName("PartsLibrary")
        PartsLibrary.resize(474, 574)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(PartsLibrary)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(PartsLibrary)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(4)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.horizontalLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWdg = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.treeWdg.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeWdg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeWdg.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeWdg.setObjectName("treeWdg")
        self.treeWdg.headerItem().setText(0, "1")
        self.treeWdg.header().setVisible(False)
        self.gridLayout_2.addWidget(self.treeWdg, 7, 0, 1, 2)
        self.cat_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cat_btn.setMaximumSize(QtCore.QSize(16777215, 15))
        self.cat_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.cat_btn.setObjectName("cat_btn")
        self.gridLayout_2.addWidget(self.cat_btn, 2, 0, 1, 1)
        self.alpha_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.alpha_btn.setMaximumSize(QtCore.QSize(16777215, 15))
        self.alpha_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.alpha_btn.setObjectName("alpha_btn")
        self.gridLayout_2.addWidget(self.alpha_btn, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_3.setStyleSheet("QFrame{background-color: rgb(55, 55, 55);}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_5.addWidget(self.lineEdit_3)
        self.alpha_btn_3 = QtWidgets.QPushButton(self.frame_3)
        self.alpha_btn_3.setMaximumSize(QtCore.QSize(60, 20))
        self.alpha_btn_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.alpha_btn_3.setObjectName("alpha_btn_3")
        self.horizontalLayout_5.addWidget(self.alpha_btn_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 2, 0, 1, 2)
        self.part_chx = QtWidgets.QCheckBox(self.frame_3)
        self.part_chx.setMaximumSize(QtCore.QSize(16777215, 15))
        self.part_chx.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.part_chx.setChecked(True)
        self.part_chx.setObjectName("part_chx")
        self.gridLayout_4.addWidget(self.part_chx, 0, 0, 1, 1)
        self.ass_chx = QtWidgets.QCheckBox(self.frame_3)
        self.ass_chx.setMaximumSize(QtCore.QSize(16777215, 15))
        self.ass_chx.setStyleSheet("background-color: rgb(55, 55, 55);")
        self.ass_chx.setChecked(True)
        self.ass_chx.setObjectName("ass_chx")
        self.gridLayout_4.addWidget(self.ass_chx, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 3, 0, 1, 2)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.docs = QtWidgets.QTextBrowser(self.layoutWidget)
        self.docs.setStyleSheet("QTextBrowser{color: rgb(140,140, 140); }")
        self.docs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.docs.setFrameShadow(QtWidgets.QFrame.Plain)
        self.docs.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.docs.setObjectName("docs")
        self.verticalLayout.addWidget(self.docs)
        self.verticalLayout_2.addWidget(self.splitter)
        self.frame_2 = QtWidgets.QFrame(PartsLibrary)
        self.frame_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.path_line = QtWidgets.QLineEdit(self.frame_2)
        self.path_line.setToolTip("")
        self.path_line.setStyleSheet("background-color: rgb(55, 55, 55);\n"
"color: rgb(150, 150, 150);")
        self.path_line.setFrame(False)
        self.path_line.setReadOnly(True)
        self.path_line.setObjectName("path_line")
        self.horizontalLayout_4.addWidget(self.path_line)
        self.browse_btn = QtWidgets.QPushButton(self.frame_2)
        self.browse_btn.setMinimumSize(QtCore.QSize(35, 20))
        self.browse_btn.setMaximumSize(QtCore.QSize(35, 20))
        self.browse_btn.setObjectName("browse_btn")
        self.horizontalLayout_4.addWidget(self.browse_btn)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(PartsLibrary)
        self.frame.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_btn = QtWidgets.QPushButton(PartsLibrary)
        self.add_btn.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_3.addWidget(self.add_btn)
        self.cancel_btn = QtWidgets.QPushButton(PartsLibrary)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_3.addWidget(self.cancel_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.setStretch(0, 1)

        self.retranslateUi(PartsLibrary)
        QtCore.QMetaObject.connectSlotsByName(PartsLibrary)

    def retranslateUi(self, PartsLibrary):
        PartsLibrary.setWindowTitle(QtCompat.translate("PartsLibrary", "Parts Library", None, -1))
        self.cat_btn.setToolTip(QtCompat.translate("PartsLibrary", "Build only selected steps in the list", None, -1))
        self.cat_btn.setText(QtCompat.translate("PartsLibrary", "Sort By Category", None, -1))
        self.alpha_btn.setToolTip(QtCompat.translate("PartsLibrary", "Build only selected steps in the list", None, -1))
        self.alpha_btn.setText(QtCompat.translate("PartsLibrary", "Sort By Name  ", None, -1))
        self.label_4.setText(QtCompat.translate("PartsLibrary", "Available Parts:", None, -1))
        self.label_6.setText(QtCompat.translate("PartsLibrary", "Filter:", None, -1))
        self.alpha_btn_3.setToolTip(QtCompat.translate("PartsLibrary", "Build only selected steps in the list", None, -1))
        self.alpha_btn_3.setText(QtCompat.translate("PartsLibrary", "Clear", None, -1))
        self.part_chx.setText(QtCompat.translate("PartsLibrary", "List Parts", None, -1))
        self.ass_chx.setText(QtCompat.translate("PartsLibrary", "List Assemblies", None, -1))
        self.label_5.setText(QtCompat.translate("PartsLibrary", "Part Info:", None, -1))
        self.label_2.setToolTip(QtCompat.translate("PartsLibrary", "Path to this assets\' rigbuild folder.", None, -1))
        self.label_2.setText(QtCompat.translate("PartsLibrary", "Module Path", None, -1))
        self.browse_btn.setToolTip(QtCompat.translate("PartsLibrary", "Open a file browser window to this rigbuild path.", None, -1))
        self.browse_btn.setText(QtCompat.translate("PartsLibrary", "...", None, -1))
        self.add_btn.setToolTip(QtCompat.translate("PartsLibrary", "Build only selected steps in the list", None, -1))
        self.add_btn.setText(QtCompat.translate("PartsLibrary", "Add Part", None, -1))
        self.cancel_btn.setText(QtCompat.translate("PartsLibrary", "Cancel", None, -1))

