# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/job/comms/google_ar_stickers_marine_4300074/sandbox/rgarcia/common/maya/2017.p5/python/rigBot/gui/pinGuidesDialog.ui'
#
# Created: Tue Nov 13 15:31:01 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtGui, QtCore, QtGui, QtWidgets

class Ui_RemapUI(object):
    def setupUi(self, RemapUI):
        RemapUI.setObjectName("RemapUI")
        RemapUI.resize(415, 682)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(RemapUI)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(RemapUI)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.orientPlcsBtn = QtWidgets.QPushButton(RemapUI)
        self.orientPlcsBtn.setObjectName("orientPlcsBtn")
        self.verticalLayout_4.addWidget(self.orientPlcsBtn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pinWorldBtn = QtWidgets.QPushButton(RemapUI)
        self.pinWorldBtn.setObjectName("pinWorldBtn")
        self.horizontalLayout_2.addWidget(self.pinWorldBtn)
        self.pinParentBtn = QtWidgets.QPushButton(RemapUI)
        self.pinParentBtn.setObjectName("pinParentBtn")
        self.horizontalLayout_2.addWidget(self.pinParentBtn)
        self.pinHierarchyBtn = QtWidgets.QPushButton(RemapUI)
        self.pinHierarchyBtn.setStyleSheet("")
        self.pinHierarchyBtn.setObjectName("pinHierarchyBtn")
        self.horizontalLayout_2.addWidget(self.pinHierarchyBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(RemapUI)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.refreshBtn = QtWidgets.QPushButton(RemapUI)
        self.refreshBtn.setObjectName("refreshBtn")
        self.verticalLayout_4.addWidget(self.refreshBtn)
        self.node_tree = QtWidgets.QTreeWidget(RemapUI)
        self.node_tree.setAlternatingRowColors(True)
        self.node_tree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.node_tree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.node_tree.setColumnCount(2)
        self.node_tree.setObjectName("node_tree")
        self.node_tree.headerItem().setText(0, "Driver")
        self.node_tree.header().setVisible(True)
        self.node_tree.header().setDefaultSectionSize(60)
        self.node_tree.header().setMinimumSectionSize(60)
        self.node_tree.header().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.node_tree)
        self.delSelectedBtn = QtWidgets.QPushButton(RemapUI)
        self.delSelectedBtn.setObjectName("delSelectedBtn")
        self.verticalLayout_4.addWidget(self.delSelectedBtn)
        self.deleteAllBtn = QtWidgets.QPushButton(RemapUI)
        self.deleteAllBtn.setObjectName("deleteAllBtn")
        self.verticalLayout_4.addWidget(self.deleteAllBtn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.printBtn = QtWidgets.QPushButton(RemapUI)
        self.printBtn.setObjectName("printBtn")
        self.verticalLayout_4.addWidget(self.printBtn)

        self.retranslateUi(RemapUI)
        QtCore.QMetaObject.connectSlotsByName(RemapUI)
        RemapUI.setTabOrder(self.pinWorldBtn, self.pinParentBtn)
        RemapUI.setTabOrder(self.pinParentBtn, self.pinHierarchyBtn)

    def retranslateUi(self, RemapUI):
        RemapUI.setWindowTitle(QtCompat.translate("RemapUI", "PinGuidesDialog UI", None, -1))
        self.label_2.setText(QtCompat.translate("RemapUI", "Create New Pins", None, -1))
        self.orientPlcsBtn.setText(QtCompat.translate("RemapUI", "Orient PLCs to Joint", None, -1))
        self.pinWorldBtn.setText(QtCompat.translate("RemapUI", "PinWorld", None, -1))
        self.pinParentBtn.setText(QtCompat.translate("RemapUI", "Pin Parent", None, -1))
        self.pinHierarchyBtn.setText(QtCompat.translate("RemapUI", "Pin Hierarchy", None, -1))
        self.label.setText(QtCompat.translate("RemapUI", "Existing Pin Groups", None, -1))
        self.refreshBtn.setText(QtCompat.translate("RemapUI", "Refresh", None, -1))
        self.node_tree.headerItem().setText(1, QtCompat.translate("RemapUI", "Driven", None, -1))
        self.delSelectedBtn.setText(QtCompat.translate("RemapUI", "Delete Selected", None, -1))
        self.deleteAllBtn.setText(QtCompat.translate("RemapUI", "Delete All Pins", None, -1))
        self.printBtn.setText(QtCompat.translate("RemapUI", "print pins", None, -1))

