# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/job/comms/google_ar_stickers_marine_4300074/sandbox/bhamilton/common/maya/2017.p5/python/rigBot/gui/remapDialog.ui'
#
# Created: Fri Sep  7 18:30:29 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!


try:
    from Qt import QtCompat, QtGui, QtCore, QtWidgets

except:
    from PySide2 import QtCompat, QtGui, QtCore, QtWidgets

class Ui_RemapUI(object):
    def setupUi(self, RemapUI):
        RemapUI.setObjectName("RemapUI")
        RemapUI.resize(412, 805)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(RemapUI)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(RemapUI)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(6, 8, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.prefixLabel = QtWidgets.QLabel(self.groupBox)
        self.prefixLabel.setObjectName("prefixLabel")
        self.gridLayout.addWidget(self.prefixLabel, 2, 0, 1, 1)
        self.prefixLine = QtWidgets.QLineEdit(self.groupBox)
        self.prefixLine.setFrame(False)
        self.prefixLine.setObjectName("prefixLine")
        self.gridLayout.addWidget(self.prefixLine, 2, 1, 1, 1)
        self.replaceLine = QtWidgets.QLineEdit(self.groupBox)
        self.replaceLine.setFrame(False)
        self.replaceLine.setObjectName("replaceLine")
        self.gridLayout.addWidget(self.replaceLine, 1, 1, 1, 1)
        self.suffixLine = QtWidgets.QLineEdit(self.groupBox)
        self.suffixLine.setFrame(False)
        self.suffixLine.setObjectName("suffixLine")
        self.gridLayout.addWidget(self.suffixLine, 3, 1, 1, 1)
        self.searchLine = QtWidgets.QLineEdit(self.groupBox)
        self.searchLine.setFrame(False)
        self.searchLine.setObjectName("searchLine")
        self.gridLayout.addWidget(self.searchLine, 0, 1, 1, 1)
        self.replaceLabel = QtWidgets.QLabel(self.groupBox)
        self.replaceLabel.setObjectName("replaceLabel")
        self.gridLayout.addWidget(self.replaceLabel, 1, 0, 1, 1)
        self.searchLabel = QtWidgets.QLabel(self.groupBox)
        self.searchLabel.setObjectName("searchLabel")
        self.gridLayout.addWidget(self.searchLabel, 0, 0, 1, 1)
        self.remapBtn = QtWidgets.QPushButton(self.groupBox)
        self.remapBtn.setObjectName("remapBtn")
        self.gridLayout.addWidget(self.remapBtn, 5, 0, 1, 2)
        self.suffixLabel = QtWidgets.QLabel(self.groupBox)
        self.suffixLabel.setObjectName("suffixLabel")
        self.gridLayout.addWidget(self.suffixLabel, 3, 0, 1, 1)
        self.mode_chx = QtWidgets.QCheckBox(self.groupBox)
        self.mode_chx.setChecked(True)
        self.mode_chx.setObjectName("mode_chx")
        self.gridLayout.addWidget(self.mode_chx, 4, 0, 1, 2)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(RemapUI)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(RemapUI)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.node_tree = QtWidgets.QTreeWidget(RemapUI)
        self.node_tree.setAlternatingRowColors(True)
        self.node_tree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.node_tree.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.node_tree.setColumnCount(3)
        self.node_tree.setObjectName("node_tree")
        self.node_tree.headerItem().setText(0, "1")
        self.node_tree.headerItem().setText(1, "2")
        self.node_tree.headerItem().setText(2, "3")
        self.node_tree.header().setVisible(True)
        self.node_tree.header().setDefaultSectionSize(60)
        self.node_tree.header().setMinimumSectionSize(60)
        self.node_tree.header().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.node_tree)
        self.filter_chx = QtWidgets.QCheckBox(RemapUI)
        self.filter_chx.setObjectName("filter_chx")
        self.verticalLayout_4.addWidget(self.filter_chx)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn = QtWidgets.QPushButton(RemapUI)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        self.reloadBtn = QtWidgets.QPushButton(RemapUI)
        self.reloadBtn.setObjectName("reloadBtn")
        self.horizontalLayout_2.addWidget(self.reloadBtn)
        self.okBtn = QtWidgets.QPushButton(RemapUI)
        self.okBtn.setStyleSheet("")
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout_2.addWidget(self.okBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(RemapUI)
        QtCore.QMetaObject.connectSlotsByName(RemapUI)
        RemapUI.setTabOrder(self.searchLine, self.replaceLine)
        RemapUI.setTabOrder(self.replaceLine, self.prefixLine)
        RemapUI.setTabOrder(self.prefixLine, self.suffixLine)
        RemapUI.setTabOrder(self.suffixLine, self.remapBtn)
        RemapUI.setTabOrder(self.remapBtn, self.node_tree)
        RemapUI.setTabOrder(self.node_tree, self.filter_chx)
        RemapUI.setTabOrder(self.filter_chx, self.cancelBtn)
        RemapUI.setTabOrder(self.cancelBtn, self.reloadBtn)
        RemapUI.setTabOrder(self.reloadBtn, self.okBtn)

    def retranslateUi(self, RemapUI):
        RemapUI.setWindowTitle(QtCompat.translate("RemapUI", "Deformer Remap UI", None, -1))
        self.groupBox.setTitle(QtCompat.translate("RemapUI", "Search && Replace Node Names", None, -1))
        self.prefixLabel.setText(QtCompat.translate("RemapUI", "Add prefix:", None, -1))
        self.replaceLabel.setText(QtCompat.translate("RemapUI", "Replace with:", None, -1))
        self.searchLabel.setText(QtCompat.translate("RemapUI", "Search for:", None, -1))
        self.remapBtn.setText(QtCompat.translate("RemapUI", "Search, Replace && Remap Nodes", None, -1))
        self.suffixLabel.setText(QtCompat.translate("RemapUI", "Add suffix:", None, -1))
        self.mode_chx.setText(QtCompat.translate("RemapUI", "Apply to unmapped only", None, -1))
        self.label.setText(QtCompat.translate("RemapUI", "Nodes To Remap", None, -1))
        self.pushButton.setText(QtCompat.translate("RemapUI", "Assign Selection To Nodes", None, -1))
        self.filter_chx.setText(QtCompat.translate("RemapUI", "Show only unmapped nodes", None, -1))
        self.cancelBtn.setText(QtCompat.translate("RemapUI", "Cancel", None, -1))
        self.reloadBtn.setText(QtCompat.translate("RemapUI", "Reset UI", None, -1))
        self.okBtn.setText(QtCompat.translate("RemapUI", "OK", None, -1))

